spring.application.name=processador

# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq

# Custom RabbitMQ Config
rabbitmq.exchange.name=pedidos.v1.pedido-criado
rabbitmq.queue.name=pedidos.v1.pedido-criado.gerar-processamento

spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos_api
spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


